branch-defaults:
  default:
    environment: dev-env
global:
  application_name: myexpress-demo
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: null
  profile: null
  sc: null